#pragma once

// Client
#define VMT_GETALLCLASSES 8
#define VMT_HUDPROCESSINPUT 10

// ClientMode
#define VMT_CREATEMOVE 24

// Vpanel
#define VMT_GETPANELNAME 36
#define VMT_PAINTTRAVERSE 41

// Surface
#define VMT_DRAWSETCOLOR 15
#define VMT_DRAWFILLEDRECT 16
#define VMT_DRAWOUTLINEDRECT 18
#define VMT_DRAWLINE 19
#define VMT_DRAWSETTEXTFONT 23
#define VMT_DRAWSETTEXTCOLOR 25
#define VMT_DRAWSETTEXTPOS 26
#define VMT_DRAWPRINTTEXT 28
#define VMT_CREATEFONT 71
#define VMT_SETFONTGLYPHSET 72

// ClientEntList
#define VMT_GETCLIENTENTITY 3
#define VMT_GETCLIENTENTITYFROMHANDLE 4
#define VMT_NUMBEROFENTITIES 5
#define VMT_GETHIGHESTENTITYINDEX 6

// Engine
#define VMT_GETSCREENSIZE 5
#define VMT_GETPLAYERINFO 8
#define VMT_GETLOCALPLAYER 12
#define VMT_SETVIEWANGLES 19
#define VMT_WORLDTOSCREENMATRIX 37
#define VMT_CLIENTCMDUNRESTRICTED 114

// EngineTrace
#define VMT_TRACERAY 5

// BaseEntity
#define VMT_SETUPBONES 13

// D3d9Device
#define VMT_ENDSCENE 42

// InputSystem
#define VMT_GETCURSORPOSITION 56

// BaseCombatWeapon
#define VMT_GETCSWPNDATA 456